---
title: "InteractiveWidgets"
author: "Bhaskar Kamble"
date: "23 Juni 2019"
output: html_document
#runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hi, just some stuff here...

```{}
#run this only if it's a shiny app
#library(htmlwidgets)
selectInput(
  'breaks', label = 'Number of bins:',
  choices = c(10, 20, 35, 50), selected = 20
)

renderPlot({
  par(mar = c(4, 4, .1, .5))
  hist(
    faithful$eruptions, as.numeric(input$breaks),
    col = 'gray', border = 'white',
    xlab = 'Duration (minutes)', main = ''
  )
})
```

```{r}
data <- data.frame(Month = c(1,2,3,4,5,6,7,8,9,10,11,12), Var1 = c(36,33,30,27,24,21,18,15,12,9,6,3), Var2 = c(4,8,12,16,20,24,28,32,36,40,44,48))
data
```

```{r}
library(plotly)
x <- seq(-2*pi, 2*pi, length.out = 1000)
df <- data.frame(x, y1 = sin(x), y2 = cos(x))
 
p <- plot_ly(df, x = ~x) %>%
  add_lines(y = ~y1, name = "A") %>%
  add_lines(y = ~y2, name = "B", visible = F)
 
 
p <- p %>% layout(
  title = "Drop down menus - Styling",
  xaxis = list(domain = c(0.1, 1)),
  yaxis = list(title = "y"),
  updatemenus = list(
    list(
      y = 0.8,
      buttons = list(
 
        list(method = "restyle",
             args = list("line.color", "blue"),
             label = "Blue"),
 
        list(method = "restyle",
             args = list("line.color", "red"),
             label = "Red"))),
 
    list(
      y = 0.7,
      buttons = list(
        list(method = "restyle",
             args = list("visible", list(TRUE, FALSE)),
             label = "Sin"),
 
        list(method = "restyle",
             args = list("visible", list(FALSE, TRUE)),
             label = "Cos")))
  ))
 
p
```

https://moderndata.plot.ly/using-the-pipe-operator-in-r-with-plotly/
http://personal.tcu.edu/kylewalker/articles/walker-2016-spatial-demography.html
https://moderndata.plot.ly/new-feature-dropdown-menus-in-plotly-and-r/
https://moderndata.plot.ly/using-the-pipe-operator-in-r-with-plotly/
https://davidgohel.github.io/ggiraph/articles/offcran/using_ggiraph.html
https://plot.ly/r/dropdowns/



```{r}
library(dplyr)
subset(mtcars,cyl==6)
```



```{r}
mtcars %>% subset(cyl==6)
```

```{r}
mean((mtcars %>% subset(cyl==6))$mpg)
```

```{r}
#library(magrittr)
#mtcars %>% subset(cyl==6) %$% mean(mpg)
```

```{r}
library(ggplot2)
mtcars %>% 
  subset(cyl == 6) %>% 
  ggplot(aes(x = wt, y = mpg)) + geom_point()
```


```{r}
ggplot(mtcars %>% subset(cyl==6) , aes(x=wt,y=mpg)) + geom_point()
```

```{r}
library(plotly)
mtcars %>% 
  subset(cyl == 6) %>% 
  plot_ly(x = ~wt, y = ~mpg) %>% 
  add_markers()
```



```{r}
  subset(mtcars,cyl == 6) %>% 
  plot_ly(x = ~wt, y = ~mpg) %>% 
  add_markers()
```



```{r}
  plot_ly(subset(mtcars,cyl == 6) , x = ~wt, y = ~mpg) %>% 
  add_markers()
```



```{r}
  add_markers(plot_ly(subset(mtcars,cyl == 6) , x = ~wt, y = ~mpg))
```


